#!/bin/bash

USER_NAME=$USER
USER_ID=`id -u`
GROUP_ID=`id -g`
GROUP_NAME=`id -gn`

BASE_IMAGE="nvcr.io/nvidia/tensorrt:23.12-py3"

TENSOR_RT_OSS_VERSION="v9.3.0"
PYCUDA_VERSION="2024.1"
# ONNX
ONNX_VERSION="1.15.0"
ONNXRUNTIME_VERSION="v1.17.1"
ONNX_TENSORRT_TAG="release/8.6-GA"
# PyTorch
TORCH_VERSION="2.2.1"
TORCHVISION_VERSION="0.17.1"
TORCH_TENSORRT_VERSION="2.2.0"

CONTAINER_NAME_PREFIX="-$(date '+%s')"

IMAGE_NAME="${USER_NAME}/torch-onnx${ONNX_VERSION//./}-${ONNXRUNTIME_VERSION//./}-trt-server:latest"

CONTAINER_NAME="${USER_NAME}-torch-onnx${ONNX_VERSION//./}-${ONNXRUNTIME_VERSION//./}-trt-server${CONTAINER_NAME_PREFIX}"