name: Deploy CUDA Python Docker Image
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuda: "12.1.1"
            python: "3.11.7"
            ubuntu: "22.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1211-python311-server:latest
          - cuda: "11.8.0"
            python: "3.11.7"
            ubuntu: "22.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1180-python311-server:latest
          - cuda: "11.8.0"
            python: "3.10.13"
            ubuntu: "22.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1180-python310-server:latest
          - cuda: "11.8.0"
            python: "3.10.13"
            ubuntu: "20.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1180-python310-ubuntu2004-server:latest
          - cuda: "11.7.1"
            python: "3.10.13"
            ubuntu: "22.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1171-python310-server:latest
          - cuda: "11.6.2"
            python: "3.10.13"
            ubuntu: "20.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1162-python310-server:latest
          - cuda: "11.3.1"
            python: "3.10.13"
            ubuntu: "20.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1131-python310-server:latest
          - cuda: "11.3.1"
            python: "3.8.16"
            ubuntu: "20.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1131-python38-server:latest
          # - cuda: "10.2"
          #   python: "3.8.16"
          #   ubuntu: "18.04"
          #   cudnn: "8"
          #   root_password: "root"
          #   get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
          #   tags: ghcr.io/mjun0812/cuda102-python38-server:latest
          # - cuda: "10.1"
          #   python: "3.8.16"
          #   ubuntu: "18.04"
          #   cudnn: "8"
          #   root_password: "root"
          #   get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
          #   tags: ghcr.io/mjun0812/cuda101-python38-server:latest
    steps:
      - name: Maximize build space
        run: |
          df -h
          echo "\n\n"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h
          echo "\n\n"

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "./cuda_python/"
          build-args: |
            PYTHON=${{ matrix.python }}
            CUDA_VERSION=${{ matrix.cuda }}
            CUDNN=${{ matrix.cudnn }}
            UBUNTU=${{ matrix.ubuntu }}
            ROOT_PASSWORD=${{ matrix.root_password }}
            GET_PIP_URL=${{ matrix.get_pip_url }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.tags }}
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ matrix.tags }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.tags }}
